version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=localhost # change this to your domain name
        - PORT=8005 # change this to your port number
    ports:
      - "8005:8005"
    volumes:
      - ./app/persistant:/app/persistant
    environment:
      - ALLOWED_ORIGINS=["http://localhost:8005"]
