version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=localhost
        - PORT=8006
    ports:
      - "8006:8006"
    volumes:
      - ./app/persistant:/app/persistant
    environment:
      - ALLOWED_ORIGINS=["http://localhost:*"]
